name: Deploy to Firebase Hosting on PR
"on":
  pull_request:
    paths: "client/**"
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - run: yarn && yarn run build
        env:
          VITE_SERVER_URL: ${{ vars.SERVER_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVELOP }}"
          projectId: project-musicloopsequencer
